package main
 
type customError struct {
     msg string
}
 
func (e *customError) Error() string {
    return e.msg
}
 
func test() *customError {
     {
         // do something
     }
     return nil
}
 
func main() {
    var err error
    err = test()
    if err != nil {
        println("error")
        return
    }
    println("ok")
}

Программа выведет error. Поскольку переменная err, имеющая интерфейсный тип, не является nil. 
Она имеет конкретное значение nil(не указывает ни на какой объект), но её динамический тип не равен nil и является customError, поэтом err != nil